apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-resume-ingress
  annotations:
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    cert-manager.io/cluster-issuer: selfsigned-issuer   # 👈 AQUÍ SE CONECTA CON CERT-MANAGER PARA HTTPs
spec:
  tls:
    - hosts: # Indica a que host se le aplicará TLS (HTTPs)
        - api1.home
        - api2.home
      secretName: cloud-resume-tls   # 👈 cert-manager creará este secret
  rules:
  - host: api1.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloud-resume-service
            port:
              number: 80
  - host: api2.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloud-resume-service
            port:
              number: 80
