apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-resume-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod   # 👈 AQUÍ SE CONECTA CON CERT-MANAGER PARA HTTPs (LET´S ENCRYPT)
spec:
  ingressClassName: traefik
  tls:
    # Define los hosts incluidos en el certificado TLS (HTTPS)
    # emitido por cert-manager y usado por este Ingress          
    - hosts:
        - api1.home.mooo.com
        - api2.home.mooo.com
      secretName: cloud-resume-tls   # 👈 cert-manager creará este secret
  rules:
  - host: api1.home.mooo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloud-resume-service
            port:
              number: 80
  - host: api2.home.mooo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloud-resume-service
            port:
              number: 80
